#ifndef MOBILE_IM_TYPE_H
#define MOBILE_IM_TYPE_H


enum
{
	MOBILE_IM_LOGIN = 1,
	MOBILE_IM_LOGOUT,
	MOBILE_IM_SEARCH_FRIEND,//查询好友信息
	MOBILE_IM_GETCONTACTLIST,//获取联系人列表
	MOBILE_IM_GETUSER_INFO,//获取用户信息
	MOBILE_IM_MODIFY_INFO,//修改用户信息
	MOBILE_IM_DELETE_FRIEDN,//删除我加的好友
	MOBILE_IM_SEND_MESSAGE,//发送消息
	MOBILE_IM_SEND_ISINPUT,//正在输入
	MOBILE_IM_MESSAGE_ISREADED,//消息已读
	MOBILE_IM_ADDFRIEND,//添加好友
	MOBILE_IM_MODIFY_PASSWORD,//修改密码
	MOBILE_IM_DELETE_ADDFRIEND,//删除加我的好友
	MOBILE_IM_SEND_TIMEOUT, //发送数据超时
	MOBILE_IM_GIVE_GIFT,
	MOBILE_IM_ADD_BLACKLIST, 
	MOBILE_IM_DELETE_BLACKLIST,
	MOBILE_IM_GET_BLACKLIST,
	MOBILE_IM_MODIFY_REMARK,		//修改备注
	MOBILE_IM_MODIFY_COORDINATE,	//修改坐标
	MOBILE_IM_MOBILE_INFO_GET,		//获取用户详情
	MOBILE_IM_MOBILE_INFO_UPDATE,	//修改用户详情
	MOBILE_IM_UPLOAD_DEVICE_INFO,	//上传设备唯一识别码，和设备类型
	MOBILE_IM_UPLOAD_PUSH_TOKEN,	//上传消息推送ID
	MOBILE_IM_ISNOT_FRIEND,		//发送消息失败
	MOBILE_IM_KEEPLIVE,
	MOBILE_IM_NEW_GIFT,					//收到新礼物
	MOBILE_IM_USER_ONLINE_NOTIFY,		//用户上线通知
	MOBILE_IM_FORCE_OFFLINE,			//强制下线
	MOBILE_IM_BC_MSG,					//系统消息
	MOBILE_IM_POPUP_MSG,				//弹出系统消息
	MOBILE_IM_GET_URL,					//获取url
	MOBILE_IM_PHONE_NUM_LOGIN,			//手机号登录
	MOBILE_IM_UPDATE_PUSH_TIMES,		//跟新消息推送计数器
	MOBILE_NEW_SITUATION_NOTIFY_USER,	//新动态通知
	MOBILE_ADD_FRIEND_MSG,				//添加好友相关信息
	MOBILE_IM_NEW_REVIEW_NOTIFY,		//新评论通知
	MOBILE_IM_GET_ROOM_ADDR,			//获取房间地址，麦码码率
	MOBILE_IM_SYS_NOTIC_NEW,			//新的系统消息
	MOBILE_IM_SEND_BINGDING_NOTIFY,		//绑定通知
	MOBILE_IM_ADD_CONNCTION_TO_IM,		//授权登录像session中增加新的conn
	MOBILE_IM_CANCEL_BINGDING_NOTIFY,	//取消绑定通知
};

enum
{

	MOBILE_IM_OK = 0,
	MOBILE_IM_FAILD,
	MOBILE_IM_WRONG_PASS,
	MOBILE_IM_IS_NOT_FRIEND,//不是好友关系
	MOBILE_IM_IN_BLACKLIST,//在黑名单中
	MOBILE_IM_FRIEND_IS_NOT_EXIT, //好友不存在
};

enum
{
	MOBILE_ADD_FRIEND_ACCEPTED,//添加成功
	MOBILE_ADD_FRIEND_AUTH_REQ,//需要验证
	MOBILE_ADD_FRIEND_REJECTED//被拒绝
};

enum
{
	MOBILE_MSG_TEXT,
	MOBILE_MSG_AUTO_REPLY,
	MOBILE_MSG_AUTH_ACCEPTED,
	MOBILE_MSG_AUTH_REQ,
	MOBILE_MSG_AUTH_REJECTED,
	MOBILE_MSG_ADDED
};

#endif


