#ifndef IM_ZYSJJJJJJZYSJJJJJJJZYSJJJJJJJJJJJ
#define IM_ZYSJJJJJJZYSJJJJJJJZYSJJJJJJJJJJJ

//enum MSG_COPYDATA_CMD
//{
//   MSG_GAME_OPEN=1,//打开游戏
//   MSG_GAME_INVITE,//邀请
//   MSG_GAME_VIEWDATA,//查看用户资料
//   MSG_GAME_ADDFREIND,//加为好友
//   MSG_GAME_SENDMSG,//发消息
//   MSG_GAME_EXITIM, //退出IM
//   MSG_LOBBY_UPDATE,//游戏更新消息
//   MSG_GANER_GAME,
//   MSG_IM_OPEN=100,
//   MSG_IM_EXIT
//};

struct  IM_PLUG_CMD
{
public:
	enum IM_PLUG_MSG_COPYDATA_CMD
	{
		IMPLUG_OPEN=0x1000,//打开游
		IMPLUG_INVITE,//邀请
		IM_PLUG_VIEWDATA,//查看用户资料
		IM_PLUG_ADDFREIND,//加为好友
		IM_PLUG_SENDMSG,//发消息
		IM_PLUG_EXITIM, //退出IM
		IM_PLUG_UPDATE,//更新消息
		IM_PLUG_GANER,
		IM_PLUG_SENDMONEY,//送银子

		IM_PLUG_KICKOUT,
		//IM_PLUG_OPEN=100,
		IM_PLUG_EXIT=0x2000,

		IM_FLASH_OPEN=0x2100,

		IM_RESUPDATE_CMD = 0x2500,
		IM_HALL_CMD = 0x3000,
		IM_GAMEBOX_CMD = 0x3100,
		IM_OPENBOX_CMD =  0x3101,
		IM_PLUG_GAMEAPPUPDATE = 0x3101,
		IM_HALL_UPLOADLOG = 0x3103,
	};
	enum CHAT_PLUG_MSG_COPYDATA_CMD
	{
		CHAT_REDPACKET_CMD = 0x7001,
		CHAT_REDPACKETREG_CMD = 0x7002,
	};
};


enum IM_PLUG_TYPE
{
	IM_PLUG_STARGAME=100,
	IM_PLUG_POKERGAME=101,
	IM_PLUG_POKERGAME_100=102,
	IM_PLUG_FLASH=200,
	IM_PLUG_BOXGAME,
	IM_PLUG_RESUPDATE,
	IM_PLUG_HALL,
	IM_PLUG_OPENBOX, //保箱游戏插件类型 added by whg 20140415
};
enum ZY_TAB
{
	VIDEO_ROOM,
	GAME_ROOM,
};

#endif

